# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ppooii12
      POSTGRES_DB: 'what-todo'
    ports:
      - 5066:5432
    volumes:
      - ./db:/var/lib/postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ppooii12
    ports:
      - 5050:80
    depends_on:
      - db

  supertokens:
    image: supertokens/supertokens-postgresql
    restart: always
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: ppooii12
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE_NAME: what-todo
    ports:
      - 3567:3567
    depends_on:
      - db